=== daily-boj/api/resources/schema/Member.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Member Schema",
  "description": "Entity represents the member of the daily-boj.",
  "examples": [
    {
      "baekjoon_id": "asdhugh1",
      "bio": "Lazy, but get Better.",
      "codeforces_id": "RanolP",
      "codeup_id": "asdhugh1",
      "display_name": "Ranolâ˜†P",
      "github_id": "RanolP",
      "gravatar_email": "public.ranolp@gmail.com",
      "id": "ranolp",
      "profile_image_url": null,
      "webpage_url": "https://twitter.com/RanolP_777"
    }
  ],
  "type": "object",
  "required": [
    "baekjoon_id",
    "display_name",
    "id"
  ],
  "properties": {
    "id": {
      "title": "Id",
      "description": "Unique ID of the member.",
      "type": "string"
    },
    "display_name": {
      "title": "Display Name",
      "description": "Display name of the member.",
      "type": "string"
    },
    "bio": {
      "title": "Bio",
      "description": "Bio of the member.",
      "type": [
        "string",
        "null"
      ]
    },
    "profile_image_url": {
      "title": "Profile Image Url",
      "description": "Profile image url of the member.",
      "type": [
        "string",
        "null"
      ]
    },
    "gravatar_email": {
      "title": "Gravatar Email",
      "description": "Gravatar email, that is used for the profile image, of the member.",
      "type": [
        "string",
        "null"
      ]
    },
    "baekjoon_id": {
      "title": "Baekjoon Id",
      "description": "Baekjoon Online Judge id of the member.",
      "type": "string"
    },
    "webpage_url": {
      "title": "Webpage Url",
      "description": "Url of a web page that belongs to the member.",
      "type": [
        "string",
        "null"
      ]
    },
    "github_id": {
      "title": "GitHub Id",
      "description": "GitHub id of the member.",
      "type": [
        "string",
        "null"
      ]
    },
    "codeforces_id": {
      "title": "CodeForces Id",
      "description": "CodeForces id of the member.",
      "type": [
        "string",
        "null"
      ]
    },
    "codeup_id": {
      "title": "CodeUp Id",
      "description": "CodeUp id of the member.",
      "type": [
        "string",
        "null"
      ]
    }
  }
}

=== daily-boj/api/database/member/ranolp.json
{
    "$schema": "../../schema/member.schema.json",
    "id": "ranolp",
    "display_name": "Ranolâ˜†P",
    "bio": "Lazy, but get Better.",
    "profile_image_url": "https://gravatar.com/avatar/8ef181fc6a8aaefd5e285af21a159c52.png?s=512",
    "gravatar_email": "public.ranolp@gmail.com",
    "baekjoon_id": "asdhugh1",
    "webpage_url": "https://twitter.com/RanolP_777",
    "github_id": "RanolP",
    "codeforces_id": "RanolP",
    "codeup_id": "asdhugh1"
}
